Fix repeat alert feature. Add "Enabled" flag to alert types. Round al…
Faifly/xDrip pull request #202
Opened 2020-10-15 13:41 UTC by Ivan-Skoryk

…l displaying glucose values to 1 digit after decimal point.

## Summary
 
 
Closes #200 
Closes #199 
Closes #196 
Closes #176 
Closes #159 

 #### Checklist:
 - [x] I have added a brief description of the problem in the PR body.
 - [x] I have explained how I solved the problem in the PR body.
 - [x] I have covered possible edge cases and side effects.
 - [x] I have have attached screenshots to the PR of any UI change.
 - [x] I have checked that my changes work on iOS and macOS targets.
 - [x] I have checked that my changes work correctly on devices with and without a Home button.
 - [x] I have added unit tests for the new logic.
 - [x] I have achieved maximum possible code coverage for the new code.
 - [x] I have checked that my UI works correctly on both Light and Dark themes.

 #### Acceptance Criteria
 

 #### Screenshots or GIFs (if appropriate)

2020-10-20 14:39 UTC, Artem-Kalmykov requested changes

2020-10-20 14:39 UTC, Artem-Kalmykov commented on xDrip/Controllers/Notifications/NotificationController.swift
> +    private func fibonicci(_ number: Int) -> Int {
`fibonacci`

2020-10-20 14:39 UTC, Artem-Kalmykov commented on xDrip/Model/Glucose/Calibration.swift
> +        NotificationCenter.default.post(name: NSNotification.Name("RegularCalibrationCreated"), object: nil)
Why `NS` and why not in a constant?

2020-10-20 14:39 UTC, Artem-Kalmykov commented on xDrip/Model/User/Settings/AlertConfiguration.swift
> +    @objc private(set) dynamic var isOverride: Bool = false
`isOverriden`

2020-10-22 15:46 UTC, Artem-Kalmykov approved these changes

2020-10-22 15:46 UTC, merged

2020-10-26 10:18 UTC, Ivan-Skoryk commented on xDrip/Model/User/Settings/AlertConfiguration.swift
> +    @objc private(set) dynamic var isEnabled: Bool = true
@qwqatest alerts already enabled by default
#200